connect("weblogic", "weblogic123", "t3://localhost:9001/console")
cd('/')
edit()
startEdit()
cd('/AppDeployments/CoherenceAdapter')
set('Targets',jarray.array([ObjectName('com.bea:Name=soa_server1,Type=Server')], ObjectName))
cd('/AppDeployments/UMSAdapter')
set('Targets',jarray.array([ObjectName('com.bea:Name=soa_server1,Type=Server')], ObjectName))
save()
activate() 